export const INITIAL_PLAYER_MODEL = {
    name: "",
    firstname: "",
    lastname: "",
    alias: "",
    card_identificacion: "",
    picture: "",
    birthday: "",
    birthplace: "",
    nationality: "",
    club: "",
    club_start: "",
    club_end: "",
    club_previous: "",
    position: "",
  }