POST http://localhost:3001/api/players
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDdkMmViZGVjMjk3OGQzNzFhOTg1ZiIsImlhdCI6MTY5MTg4NTY5MSwiZXhwIjoxNjkxOTcyMDkxfQ.7uOQNMhZe_saV13u8EYrAJBOZ-CJ6FfLmogtyBZ4r9o

{
    "name": "Pepe",
    "position": "Portero",
    "birthday": "2000-02-25"
}

###

POST http://localhost:3001/api/players
Content-Type: application/json

{
}